// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukgszfsyaxhrrmppprtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZ3N6ZnN5YXhocnJtcHBwcnRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTc2NjAsImV4cCI6MjA2NTUzMzY2MH0.BrOQ0WqPrIUv4Xy3WLZ3cukfIgoNaRXWbwltm5DHeLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);